### ISSUE TITLE
[Bug] Timestamp for last file is a few seconds short

### ISSUE THREAD

**Issue by Tenome** [MartinBarker/RenderTune#14]
I'm not sure how RT calculates the length/timestamps, but I noticed that the estimation was a bit short on the last track at least. I confirmed in Audacity as well that the first length is correct.

https://puu.sh/IrHD2/01ddb7b745.png
https://puu.sh/IrHCp/18831158be.png

**Comment by MartinBarker** [comment]
Yes sometimes the audio timestamps are not perfect, I see this on my website www.tagger.site as well.
Although I would say that having the last timestamp off by a couple seconds is not that big of an issue, perfectly accurate timestamps would be nice though but in my findings they vary not too noticeably

**Comment by MartinBarker** [comment]
timestamp calculation seems correct, its the output video that is appending some silent space to the end of it. I'm working on a new version ( 1.2.0 ) which will fix this

**Comment by MartinBarker** [comment]
Just released v1.1.1, on apple store, linux snap store, windows store review still in process. new files in version on this github.

Included better timestamp logic
